USE Testeando
GO
SET IMPLICIT_TRANSACTIONS ON;
-- EL BEGIN SE SETEA EN AUTOMATICO Y SE CIERRA CON EL COMMIT
--INSERT INTO Alumnos VALUES (13, 'Ulises Moreno', 34);
--COMMIT;
--DELETE FROM Alumnos WHERE ID = 13;
--ROLLBACK;
UPDATE Alumnos SET Edad = Edad + 5 WHERE ID = 14;
ROLLBACK;
SET IMPLICIT_TRANSACTIONS OFF;
SELECT * FROM Alumnos;