CREATE DATABASE BD_TIGGERS;
GO

USE BD_TIGGERS
GO
CREATE TABLE Empleados (
	IdEmpleado INT IDENTITY(1,1) PRIMARY KEY,
	Nombre NVARCHAR(100) NOT NULL,
	Puesto NVARCHAR(100),
	Sueldo DECIMAL (10,2),
	FechaIngreso DATE DEFAULT GETDATE()
);

CREATE TABLE Auditoria (
	IdAuditoria INT IDENTITY(1,1) PRIMARY KEY,
	Usuario NVARCHAR(100),
	Fecha DATETIME DEFAULT GETDATE(),
	Accion NVARCHAR(200)
);
GO